classdef Ray < handle

  properties
    origin;
    position;
    direction;
    distancePerStep = 0.01;
    numberOfSteps = 500;
    currentIoR = 1.0;
  endproperties

  methods
      % Constructor
      function obj = Ray(origin, angle)
        % Initialize variables
        obj.origin = origin;
        obj.position = origin;
        obj.direction = [cos(angle),sin(angle)];

        % Check all objects in the scene to get the initial index of refraction
        sceneObjects = get(gca,'userdata');
        for i = 1:length(sceneObjects)
          is_inside = obj.point_in_polygon(obj.origin, sceneObjects{i}.position);

          if is_inside && ~sceneObjects{i}.reflective
            obj.currentIoR = sceneObjects{i}.indexOfRefraction;
            break;
          elseif is_inside && sceneObjects{i}.reflective
            error('Error: The origin of the ray is located within a reflective object.');
          endif
        endfor

        % Main ray tracing program
        obj.computeRayPath();
        obj.render();
      endfunction

      % Compute ray path
      function computeRayPath(obj)

        for step = 2:obj.numberOfSteps
          obj.position(step,:) = obj.position(step-1,:) + (obj.direction .* obj.distancePerStep);

          [intersectsObject, intersectedObjIndex, intersectedFaceIndex, intersectionPoint] = obj.checkForIntersection(step);
          if intersectsObject
            % Update the current ray position to the intersection point
            obj.position(step,:) = intersectionPoint;

            %disp('Intersection detected!');
            %disp(['The ray intersects object number ',int2str(intersectedObjIndex),' on face number ',int2str(intersectedFaceIndex),' at point [', num2str(intersectionPoint(1)),' , ', num2str(intersectionPoint(2)),'].']);
            % Check the type of object in the scene that the ray is going to interact with
            sceneObject = get(gca,'userdata'){intersectedObjIndex};
            if sceneObject.reflective
              % Totally reflect the ray by changing the direction using the normal vector and the intersection point
              reflectionNormal = sceneObject.normal(intersectedFaceIndex,:);
              obj.direction = obj.direction - (2*dot(obj.direction,reflectionNormal).*reflectionNormal);

            elseif ~sceneObject.reflective
              % Refract the ray based on snells law

              % Get the incoming and normal vector
              incomingVector = obj.position(step,:) - obj.position(step-1,:);
              normalVector = sceneObject.normal(intersectedFaceIndex,:);

              % Calculate the angle of incidence (w.r.t. normal vector)
              incident_angle = mod(pi,acos(dot(incomingVector,normalVector) ./ (norm(incomingVector)*norm(normalVector))));

              % Firstly, check for total internal reflection is possible...
              if (sceneObject.indexOfRefraction / obj.currentIoR) < 1
                % If it is possible, then first calculate the critical angle
                critical_angle = asin(sceneObject.indexOfRefraction / obj.currentIoR);

                if incident_angle > critical_angle
                  % Total internal reflection

                  % TODO: add and check this. the current code may cause problems with the ray being already inside an object

                endif
              endif
              break;

            endif
          endif
        endfor
      endfunction

      % Render
      function render(obj)
        hold(gca,'on');
        plot(gca, obj.position(:,1), obj.position(:,2),'r-');
        hold(gca,'off');
      endfunction

      %--- Intersection code ---%
      % This was generated by chatGPT, so I do not fully understand how it
      % works, but it does sooooo...

      % Check for intersection
      function [intersectsObject, intersectedObjIndex, intersectedFaceIndex, intersectionPoint] = checkForIntersection(obj,step)
        scene = get(gca,'userdata');
        intersectsObject = false;
        intersectedObjIndex = [];
        intersectedFaceIndex = [];
        intersectionPoint = [];

        % Loop through each object in the scene
        for objs = 1:length(scene)
          sceneObj = scene{objs};

          %--- Intersection checking ---%
          % To see if there is a valid intersection, we must first check if the
          % current position of the ray is within the object that we are looping
          % through
          is_inside = obj.point_in_polygon(obj.position(step,:), sceneObj.position);

          % If the point is within a polygon, set the flag, and find the
          % location of the intersection by computing the intersection of line
          % segments
          if is_inside
            intersectsObject = true;
            intersectedObjIndex = objs;

            % Compute the intersection of line segments
            for i = 1:size(sceneObj.position,1)
              [intersectsFace, intersectionPoint] = obj.line_segment_intersection(obj.position(step-1,:), obj.position(step,:),...
                                                                           sceneObj.position(i,:), sceneObj.position(mod(i, length(sceneObj.position)) + 1, :));
              if intersectsFace
                intersectedFaceIndex = i;
                break;
              endif
            endfor

            break;
          endif
        endfor
      endfunction

      function inside = point_in_polygon(obj, point, polygon_vertices)
        % point = (x, y) - the point to check
        % polygon = an Nx2 matrix of vertices [x1, y1; x2, y2; ...; xn, yn]

        % Extract the coordinates of the point
        x = point(1);
        y = point(2);

        % Get the number of vertices of the polygon
        n = size(polygon_vertices, 1);

        % Initialize the number of intersections
        intersections = 0;

        for i = 1:n
          % Get the current edge from the polygon
          x1 = polygon_vertices(i, 1);
          y1 = polygon_vertices(i, 2);
          x2 = polygon_vertices(mod(i, n) + 1, 1);  % Wrap around for the last vertex
          y2 = polygon_vertices(mod(i, n) + 1, 2);  % Wrap around for the last vertex

          % Check if the ray from point (x, y) intersects the edge (x1, y1) → (x2, y2)
          if ((y1 > y && y2 <= y) || (y2 > y && y1 <= y))  % Check if the point's y is between the edge's y-values
            % Calculate the x-coordinate of the intersection point of the ray with the edge
            intersect_x = (y - y1) * (x2 - x1) / (y2 - y1) + x1;

            % Check if the intersection point is to the right of the point
            if (intersect_x > x)
              intersections = intersections + 1;
            endif
          endif
        endfor

        % If the number of intersections is odd, the point is inside
        inside = mod(intersections, 2) == 1;
      endfunction

      function [intersect, intersection_point] = line_segment_intersection(obj, A, B, C, D)
        % Compute the differences between points
        dx1 = B(1) - A(1);
        dy1 = B(2) - A(2);
        dx2 = D(1) - C(1);
        dy2 = D(2) - C(2);

        % Set up the system of equations
        denom = (dx1 * dy2) - (dy1 * dx2);

        % If denom is 0, the lines are parallel or collinear
        if denom == 0
            intersect = false;
            intersection_point = [];
            return;
        endif

        % Compute the parameters t and u
        dx3 = C(1) - A(1);
        dy3 = C(2) - A(2);

        t = (dx3 * dy2 - dy3 * dx2) / denom;
        u = (dx3 * dy1 - dy3 * dx1) / denom;

        % Check if the intersection point is within both line segments
        if t >= 0 && t <= 1 && u >= 0 && u <= 1
            intersect = true;
            % Calculate the intersection point using t
            intersection_point = [A(1) + t * dx1, A(2) + t * dy1];
        else
            intersect = false;
            intersection_point = [];
        endif
      endfunction

  endmethods
endclassdef

